# Site settings
name: BuddyUp Spec
title: BuddyUp Spec
email: mhanratty@mozilla.com
description: "Specifications for BuddyUp"
# these need to be changed for each project
baseurl: "/marketplaceux-buddyup" #this is the github project name WITHOUT the trailing /
url: "https://mhanratty.github.io"  #this the url of the GHPages account your project is hosted at

# Build settings
markdown: kramdown
permalinks: pretty
